CREATE TABLE Groupe (
        GROUPE_ID INTEGER NOT NULL,
        GROUPENAME  VARCHAR(15),
        PRIMARY KEY (GROUPE_ID)
);

CREATE TABLE Student(

    STUDENT_ID INTEGER NOT NULL,  
    STUDENTFIRSTNAME VARCHAR(15),
    STUDENTLASTNAME VARCHAR(15),
    PRIMARY KEY (STUDENT_ID),
	GROUPE_ID INTEGER NOT NULL,
	FOREIGN KEY (GROUPE_ID) REFERENCES Groupe(GROUPE_ID)

);



